// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofunrwrfeqhbkowoosns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mdW5yd3JmZXFoYmtvd29vc25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTI1NTUsImV4cCI6MjA2OTg2ODU1NX0.9VRx9x7c73F5zxdQVkfvaGoTWcrMQk5w7YJDM8WWnMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});